// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: RobotService.proto

package Robot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HasReceivedTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Confirmation string `protobuf:"bytes,1,opt,name=confirmation,proto3" json:"confirmation,omitempty"`
}

func (x *HasReceivedTask) Reset() {
	*x = HasReceivedTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RobotService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasReceivedTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasReceivedTask) ProtoMessage() {}

func (x *HasReceivedTask) ProtoReflect() protoreflect.Message {
	mi := &file_RobotService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasReceivedTask.ProtoReflect.Descriptor instead.
func (*HasReceivedTask) Descriptor() ([]byte, []int) {
	return file_RobotService_proto_rawDescGZIP(), []int{0}
}

func (x *HasReceivedTask) GetConfirmation() string {
	if x != nil {
		return x.Confirmation
	}
	return ""
}

type Instructions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instruction []int32 `protobuf:"varint,1,rep,packed,name=instruction,proto3" json:"instruction,omitempty"`
}

func (x *Instructions) Reset() {
	*x = Instructions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RobotService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Instructions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instructions) ProtoMessage() {}

func (x *Instructions) ProtoReflect() protoreflect.Message {
	mi := &file_RobotService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instructions.ProtoReflect.Descriptor instead.
func (*Instructions) Descriptor() ([]byte, []int) {
	return file_RobotService_proto_rawDescGZIP(), []int{1}
}

func (x *Instructions) GetInstruction() []int32 {
	if x != nil {
		return x.Instruction
	}
	return nil
}

var File_RobotService_proto protoreflect.FileDescriptor

var file_RobotService_proto_rawDesc = []byte{
	0x0a, 0x12, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x35, 0x0a, 0x0f, 0x68, 0x61,
	0x73, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x22, 0x0a,
	0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x30, 0x0a, 0x0c, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x32, 0x49, 0x0a, 0x0b, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x54, 0x61,
	0x73, 0x6b, 0x12, 0x3a, 0x0a, 0x0b, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x54, 0x61, 0x73,
	0x6b, 0x12, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x15, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x68, 0x61, 0x73,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x22, 0x00, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x2f, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_RobotService_proto_rawDescOnce sync.Once
	file_RobotService_proto_rawDescData = file_RobotService_proto_rawDesc
)

func file_RobotService_proto_rawDescGZIP() []byte {
	file_RobotService_proto_rawDescOnce.Do(func() {
		file_RobotService_proto_rawDescData = protoimpl.X.CompressGZIP(file_RobotService_proto_rawDescData)
	})
	return file_RobotService_proto_rawDescData
}

var file_RobotService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_RobotService_proto_goTypes = []interface{}{
	(*HasReceivedTask)(nil), // 0: main.hasReceivedTask
	(*Instructions)(nil),    // 1: main.Instructions
}
var file_RobotService_proto_depIdxs = []int32{
	1, // 0: main.ReceiveTask.ReceiveTask:input_type -> main.Instructions
	0, // 1: main.ReceiveTask.ReceiveTask:output_type -> main.hasReceivedTask
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_RobotService_proto_init() }
func file_RobotService_proto_init() {
	if File_RobotService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_RobotService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HasReceivedTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RobotService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Instructions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_RobotService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_RobotService_proto_goTypes,
		DependencyIndexes: file_RobotService_proto_depIdxs,
		MessageInfos:      file_RobotService_proto_msgTypes,
	}.Build()
	File_RobotService_proto = out.File
	file_RobotService_proto_rawDesc = nil
	file_RobotService_proto_goTypes = nil
	file_RobotService_proto_depIdxs = nil
}
