// Code generated by protoc-gen-go. DO NOT EDIT.
// source: theHive/RobotService/botClientService.RobotService

package botClientService

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//Point information, for requests and logging of positions
type Point struct {
	XPosition            int32    `protobuf:"varint,1,opt,name=XPosition,proto3" json:"XPosition,omitempty"`
	YPosition            int32    `protobuf:"varint,2,opt,name=YPosition,proto3" json:"YPosition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_53edd005e8ff559b, []int{0}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetXPosition() int32 {
	if m != nil {
		return m.XPosition
	}
	return 0
}

func (m *Point) GetYPosition() int32 {
	if m != nil {
		return m.YPosition
	}
	return 0
}

//Conformation message at end of client stream(wall-e) to server(hive)
type MessageRecieved struct {
	Recieved             bool     `protobuf:"varint,1,opt,name=Recieved,proto3" json:"Recieved,omitempty"`
	NumberOfMessages     int32    `protobuf:"varint,2,opt,name=NumberOfMessages,proto3" json:"NumberOfMessages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRecieved) Reset()         { *m = MessageRecieved{} }
func (m *MessageRecieved) String() string { return proto.CompactTextString(m) }
func (*MessageRecieved) ProtoMessage()    {}
func (*MessageRecieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_53edd005e8ff559b, []int{1}
}

func (m *MessageRecieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRecieved.Unmarshal(m, b)
}
func (m *MessageRecieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRecieved.Marshal(b, m, deterministic)
}
func (m *MessageRecieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRecieved.Merge(m, src)
}
func (m *MessageRecieved) XXX_Size() int {
	return xxx_messageInfo_MessageRecieved.Size(m)
}
func (m *MessageRecieved) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRecieved.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRecieved proto.InternalMessageInfo

func (m *MessageRecieved) GetRecieved() bool {
	if m != nil {
		return m.Recieved
	}
	return false
}

func (m *MessageRecieved) GetNumberOfMessages() int32 {
	if m != nil {
		return m.NumberOfMessages
	}
	return 0
}

func init() {
	proto.RegisterType((*Point)(nil), "botClientService.Point")
	proto.RegisterType((*MessageRecieved)(nil), "botClientService.MessageRecieved")
}

func init() {
	proto.RegisterFile("theHive/RobotService/botClientService.RobotService", fileDescriptor_53edd005e8ff559b)
}

var fileDescriptor_53edd005e8ff559b = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x29, 0xc9, 0x48, 0xf5,
	0xc8, 0x2c, 0x4b, 0xd5, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0xca, 0x2f, 0x71, 0xce, 0xc9,
	0x4c, 0xcd, 0x2b, 0x09, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x03, 0x0b, 0x0b, 0x09, 0xa0,
	0x8b, 0x2b, 0x39, 0x73, 0xb1, 0x06, 0xe4, 0x67, 0xe6, 0x95, 0x08, 0xc9, 0x70, 0x71, 0x46, 0x04,
	0xe4, 0x17, 0x67, 0x96, 0x64, 0xe6, 0xe7, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x21, 0x04,
	0x40, 0xb2, 0x91, 0x70, 0x59, 0x26, 0x88, 0x2c, 0x5c, 0x40, 0x29, 0x92, 0x8b, 0xdf, 0x37, 0xb5,
	0xb8, 0x38, 0x31, 0x3d, 0x35, 0x28, 0x35, 0x39, 0x33, 0xb5, 0x2c, 0x35, 0x45, 0x48, 0x8a, 0x8b,
	0x03, 0xc6, 0x06, 0x9b, 0xc6, 0x11, 0x04, 0xe7, 0x0b, 0x69, 0x71, 0x09, 0xf8, 0x95, 0xe6, 0x26,
	0xa5, 0x16, 0xf9, 0xa7, 0x41, 0xb5, 0x15, 0x43, 0xcd, 0xc4, 0x10, 0x37, 0xca, 0xe5, 0x12, 0x70,
	0x42, 0x73, 0xb3, 0x50, 0x24, 0x97, 0x78, 0x50, 0x6a, 0x7a, 0x66, 0x71, 0x49, 0x6a, 0x91, 0x73,
	0x69, 0x51, 0x51, 0x6a, 0x5e, 0x09, 0xdc, 0x9d, 0xe2, 0x7a, 0x18, 0x3e, 0x07, 0x7b, 0x4f, 0x4a,
	0x11, 0x53, 0x02, 0xcd, 0xc9, 0x4a, 0x0c, 0x1a, 0x8c, 0x49, 0x6c, 0xe0, 0x70, 0x32, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x54, 0x76, 0x34, 0x27, 0x4f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BotClientServiceClient is the client API for BotClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BotClientServiceClient interface {
	//Streams updates of each robot position on the grid
	RegisterCurrentPosition(ctx context.Context, opts ...grpc.CallOption) (BotClientService_RegisterCurrentPositionClient, error)
}

type botClientServiceClient struct {
	cc *grpc.ClientConn
}

func NewBotClientServiceClient(cc *grpc.ClientConn) BotClientServiceClient {
	return &botClientServiceClient{cc}
}

func (c *botClientServiceClient) RegisterCurrentPosition(ctx context.Context, opts ...grpc.CallOption) (BotClientService_RegisterCurrentPositionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BotClientService_serviceDesc.Streams[0], "/botClientService.BotClientService/RegisterCurrentPosition", opts...)
	if err != nil {
		return nil, err
	}
	x := &botClientServiceRegisterCurrentPositionClient{stream}
	return x, nil
}

type BotClientService_RegisterCurrentPositionClient interface {
	Send(*Point) error
	CloseAndRecv() (*MessageRecieved, error)
	grpc.ClientStream
}

type botClientServiceRegisterCurrentPositionClient struct {
	grpc.ClientStream
}

func (x *botClientServiceRegisterCurrentPositionClient) Send(m *Point) error {
	return x.ClientStream.SendMsg(m)
}

func (x *botClientServiceRegisterCurrentPositionClient) CloseAndRecv() (*MessageRecieved, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(MessageRecieved)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BotClientServiceServer is the server API for BotClientService service.
type BotClientServiceServer interface {
	//Streams updates of each robot position on the grid
	RegisterCurrentPosition(BotClientService_RegisterCurrentPositionServer) error
}

// UnimplementedBotClientServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBotClientServiceServer struct {
}

func (*UnimplementedBotClientServiceServer) RegisterCurrentPosition(srv BotClientService_RegisterCurrentPositionServer) error {
	return status.Errorf(codes.Unimplemented, "method RegisterCurrentPosition not implemented")
}

func RegisterBotClientServiceServer(s *grpc.Server, srv BotClientServiceServer) {
	s.RegisterService(&_BotClientService_serviceDesc, srv)
}

func _BotClientService_RegisterCurrentPosition_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BotClientServiceServer).RegisterCurrentPosition(&botClientServiceRegisterCurrentPositionServer{stream})
}

type BotClientService_RegisterCurrentPositionServer interface {
	SendAndClose(*MessageRecieved) error
	Recv() (*Point, error)
	grpc.ServerStream
}

type botClientServiceRegisterCurrentPositionServer struct {
	grpc.ServerStream
}

func (x *botClientServiceRegisterCurrentPositionServer) SendAndClose(m *MessageRecieved) error {
	return x.ServerStream.SendMsg(m)
}

func (x *botClientServiceRegisterCurrentPositionServer) Recv() (*Point, error) {
	m := new(Point)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _BotClientService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "botClientService.BotClientService",
	HandlerType: (*BotClientServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterCurrentPosition",
			Handler:       _BotClientService_RegisterCurrentPosition_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "theHive/RobotService/botClientService.RobotService",
}
