// Code generated by protoc-gen-go. DO NOT EDIT.
// source: theHive/proto/botClientService.proto

package botClientService

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//Point information, for requests and logging of positions
type Point struct {
	RobotId              string   `protobuf:"bytes,1,opt,name=RobotId,proto3" json:"RobotId,omitempty"`
	XPosition            int32    `protobuf:"varint,2,opt,name=XPosition,proto3" json:"XPosition,omitempty"`
	YPosition            int32    `protobuf:"varint,3,opt,name=YPosition,proto3" json:"YPosition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_53edd005e8ff559b, []int{0}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetRobotId() string {
	if m != nil {
		return m.RobotId
	}
	return ""
}

func (m *Point) GetXPosition() int32 {
	if m != nil {
		return m.XPosition
	}
	return 0
}

func (m *Point) GetYPosition() int32 {
	if m != nil {
		return m.YPosition
	}
	return 0
}

//Conformation message at end of client stream(wall-e) to server(hive)
type MessageRecieved struct {
	Recieved             bool     `protobuf:"varint,1,opt,name=Recieved,proto3" json:"Recieved,omitempty"`
	NumberOfMessages     int32    `protobuf:"varint,2,opt,name=NumberOfMessages,proto3" json:"NumberOfMessages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRecieved) Reset()         { *m = MessageRecieved{} }
func (m *MessageRecieved) String() string { return proto.CompactTextString(m) }
func (*MessageRecieved) ProtoMessage()    {}
func (*MessageRecieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_53edd005e8ff559b, []int{1}
}

func (m *MessageRecieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRecieved.Unmarshal(m, b)
}
func (m *MessageRecieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRecieved.Marshal(b, m, deterministic)
}
func (m *MessageRecieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRecieved.Merge(m, src)
}
func (m *MessageRecieved) XXX_Size() int {
	return xxx_messageInfo_MessageRecieved.Size(m)
}
func (m *MessageRecieved) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRecieved.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRecieved proto.InternalMessageInfo

func (m *MessageRecieved) GetRecieved() bool {
	if m != nil {
		return m.Recieved
	}
	return false
}

func (m *MessageRecieved) GetNumberOfMessages() int32 {
	if m != nil {
		return m.NumberOfMessages
	}
	return 0
}

//Position of the robot on the grid.
type GridPositions struct {
	RobotId              string   `protobuf:"bytes,1,opt,name=RobotId,proto3" json:"RobotId,omitempty"`
	XPosition            int32    `protobuf:"varint,2,opt,name=XPosition,proto3" json:"XPosition,omitempty"`
	YPosition            int32    `protobuf:"varint,3,opt,name=YPosition,proto3" json:"YPosition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GridPositions) Reset()         { *m = GridPositions{} }
func (m *GridPositions) String() string { return proto.CompactTextString(m) }
func (*GridPositions) ProtoMessage()    {}
func (*GridPositions) Descriptor() ([]byte, []int) {
	return fileDescriptor_53edd005e8ff559b, []int{2}
}

func (m *GridPositions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GridPositions.Unmarshal(m, b)
}
func (m *GridPositions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GridPositions.Marshal(b, m, deterministic)
}
func (m *GridPositions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GridPositions.Merge(m, src)
}
func (m *GridPositions) XXX_Size() int {
	return xxx_messageInfo_GridPositions.Size(m)
}
func (m *GridPositions) XXX_DiscardUnknown() {
	xxx_messageInfo_GridPositions.DiscardUnknown(m)
}

var xxx_messageInfo_GridPositions proto.InternalMessageInfo

func (m *GridPositions) GetRobotId() string {
	if m != nil {
		return m.RobotId
	}
	return ""
}

func (m *GridPositions) GetXPosition() int32 {
	if m != nil {
		return m.XPosition
	}
	return 0
}

func (m *GridPositions) GetYPosition() int32 {
	if m != nil {
		return m.YPosition
	}
	return 0
}

//Payload returned if robot registration was successful
type RobotRegistrationSuccess struct {
	RobotId              string   `protobuf:"bytes,1,opt,name=RobotId,proto3" json:"RobotId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RobotRegistrationSuccess) Reset()         { *m = RobotRegistrationSuccess{} }
func (m *RobotRegistrationSuccess) String() string { return proto.CompactTextString(m) }
func (*RobotRegistrationSuccess) ProtoMessage()    {}
func (*RobotRegistrationSuccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_53edd005e8ff559b, []int{3}
}

func (m *RobotRegistrationSuccess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RobotRegistrationSuccess.Unmarshal(m, b)
}
func (m *RobotRegistrationSuccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RobotRegistrationSuccess.Marshal(b, m, deterministic)
}
func (m *RobotRegistrationSuccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RobotRegistrationSuccess.Merge(m, src)
}
func (m *RobotRegistrationSuccess) XXX_Size() int {
	return xxx_messageInfo_RobotRegistrationSuccess.Size(m)
}
func (m *RobotRegistrationSuccess) XXX_DiscardUnknown() {
	xxx_messageInfo_RobotRegistrationSuccess.DiscardUnknown(m)
}

var xxx_messageInfo_RobotRegistrationSuccess proto.InternalMessageInfo

func (m *RobotRegistrationSuccess) GetRobotId() string {
	if m != nil {
		return m.RobotId
	}
	return ""
}

func init() {
	proto.RegisterType((*Point)(nil), "main.Point")
	proto.RegisterType((*MessageRecieved)(nil), "main.MessageRecieved")
	proto.RegisterType((*GridPositions)(nil), "main.GridPositions")
	proto.RegisterType((*RobotRegistrationSuccess)(nil), "main.RobotRegistrationSuccess")
}

func init() {
	proto.RegisterFile("theHive/proto/botClientService.proto", fileDescriptor_53edd005e8ff559b)
}

var fileDescriptor_53edd005e8ff559b = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xcd, 0x4a, 0x03, 0x31,
	0x10, 0xc7, 0xbb, 0x6a, 0xb5, 0x1d, 0x29, 0x96, 0xa8, 0xb8, 0x2c, 0x22, 0x65, 0xf1, 0xb0, 0x78,
	0xd8, 0x82, 0xfa, 0x02, 0xb6, 0xe0, 0xc7, 0x41, 0x2d, 0xe9, 0xc5, 0x0a, 0x1e, 0xf6, 0x63, 0xac,
	0x03, 0x36, 0x91, 0x24, 0xbb, 0x6f, 0xe3, 0xbb, 0xca, 0x26, 0xdd, 0x15, 0x5b, 0xf4, 0xe6, 0x2d,
	0xf3, 0x9b, 0x64, 0xfe, 0x93, 0xff, 0x0c, 0x9c, 0x9a, 0x37, 0xbc, 0xa5, 0x12, 0x87, 0x1f, 0x4a,
	0x1a, 0x39, 0x4c, 0xa5, 0x19, 0xbf, 0x13, 0x0a, 0x33, 0x45, 0x55, 0x52, 0x86, 0xb1, 0xc5, 0x6c,
	0x6b, 0x91, 0x90, 0x08, 0x5f, 0xa0, 0x3d, 0x91, 0x24, 0x0c, 0xf3, 0x61, 0x87, 0xcb, 0x54, 0x9a,
	0xbb, 0xdc, 0xf7, 0x06, 0x5e, 0xd4, 0xe5, 0x75, 0xc8, 0x8e, 0xa1, 0xfb, 0x34, 0x91, 0x9a, 0x0c,
	0x49, 0xe1, 0x6f, 0x0c, 0xbc, 0xa8, 0xcd, 0xbf, 0x41, 0x95, 0x9d, 0x35, 0xd9, 0x4d, 0x97, 0x6d,
	0x40, 0x38, 0x83, 0xbd, 0x7b, 0xd4, 0x3a, 0x99, 0x23, 0xc7, 0x8c, 0xb0, 0xc4, 0x9c, 0x05, 0xd0,
	0xa9, 0xcf, 0x56, 0xa9, 0xc3, 0x9b, 0x98, 0x9d, 0x41, 0xff, 0xa1, 0x58, 0xa4, 0xa8, 0x1e, 0x5f,
	0x97, 0xcf, 0xf4, 0x52, 0x71, 0x8d, 0x87, 0x08, 0xbd, 0x1b, 0x45, 0x79, 0x2d, 0xa5, 0xff, 0xe9,
	0x07, 0x97, 0xe0, 0xdb, 0x32, 0x1c, 0xe7, 0xa4, 0x8d, 0x4a, 0x2a, 0x38, 0x2d, 0xb2, 0x0c, 0xf5,
	0x1f, 0x8a, 0xe7, 0x9f, 0x1e, 0xf4, 0x47, 0x2b, 0xbe, 0xb3, 0x2b, 0x38, 0x72, 0x55, 0x50, 0x8d,
	0x0b, 0xa5, 0x50, 0x98, 0xa6, 0x87, 0xdd, 0xb8, 0x9a, 0x46, 0x6c, 0x47, 0x11, 0x1c, 0xba, 0x60,
	0xc5, 0xb8, 0xb0, 0x15, 0x79, 0xec, 0x1a, 0x7a, 0x75, 0x09, 0x2b, 0xc5, 0xf6, 0xdd, 0xdd, 0x1f,
	0x4e, 0x04, 0x27, 0x0e, 0xfe, 0xd6, 0x77, 0xd8, 0x1a, 0x1d, 0x3c, 0xb3, 0x78, 0x6d, 0x31, 0xd2,
	0x6d, 0xbb, 0x19, 0x17, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa0, 0xd4, 0x8f, 0xf1, 0x41, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BotClientServiceClient is the client API for BotClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BotClientServiceClient interface {
	//Streams updates from each robot position on the grid to the hive
	RegisterCurrentPosition(ctx context.Context, opts ...grpc.CallOption) (BotClientService_RegisterCurrentPositionClient, error)
	RegisterRobot(ctx context.Context, in *GridPositions, opts ...grpc.CallOption) (*RobotRegistrationSuccess, error)
}

type botClientServiceClient struct {
	cc *grpc.ClientConn
}

func NewBotClientServiceClient(cc *grpc.ClientConn) BotClientServiceClient {
	return &botClientServiceClient{cc}
}

func (c *botClientServiceClient) RegisterCurrentPosition(ctx context.Context, opts ...grpc.CallOption) (BotClientService_RegisterCurrentPositionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BotClientService_serviceDesc.Streams[0], "/main.BotClientService/RegisterCurrentPosition", opts...)
	if err != nil {
		return nil, err
	}
	x := &botClientServiceRegisterCurrentPositionClient{stream}
	return x, nil
}

type BotClientService_RegisterCurrentPositionClient interface {
	Send(*Point) error
	CloseAndRecv() (*MessageRecieved, error)
	grpc.ClientStream
}

type botClientServiceRegisterCurrentPositionClient struct {
	grpc.ClientStream
}

func (x *botClientServiceRegisterCurrentPositionClient) Send(m *Point) error {
	return x.ClientStream.SendMsg(m)
}

func (x *botClientServiceRegisterCurrentPositionClient) CloseAndRecv() (*MessageRecieved, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(MessageRecieved)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *botClientServiceClient) RegisterRobot(ctx context.Context, in *GridPositions, opts ...grpc.CallOption) (*RobotRegistrationSuccess, error) {
	out := new(RobotRegistrationSuccess)
	err := c.cc.Invoke(ctx, "/main.BotClientService/RegisterRobot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BotClientServiceServer is the server API for BotClientService service.
type BotClientServiceServer interface {
	//Streams updates from each robot position on the grid to the hive
	RegisterCurrentPosition(BotClientService_RegisterCurrentPositionServer) error
	RegisterRobot(context.Context, *GridPositions) (*RobotRegistrationSuccess, error)
}

// UnimplementedBotClientServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBotClientServiceServer struct {
}

func (*UnimplementedBotClientServiceServer) RegisterCurrentPosition(srv BotClientService_RegisterCurrentPositionServer) error {
	return status.Errorf(codes.Unimplemented, "method RegisterCurrentPosition not implemented")
}
func (*UnimplementedBotClientServiceServer) RegisterRobot(ctx context.Context, req *GridPositions) (*RobotRegistrationSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterRobot not implemented")
}

func RegisterBotClientServiceServer(s *grpc.Server, srv BotClientServiceServer) {
	s.RegisterService(&_BotClientService_serviceDesc, srv)
}

func _BotClientService_RegisterCurrentPosition_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BotClientServiceServer).RegisterCurrentPosition(&botClientServiceRegisterCurrentPositionServer{stream})
}

type BotClientService_RegisterCurrentPositionServer interface {
	SendAndClose(*MessageRecieved) error
	Recv() (*Point, error)
	grpc.ServerStream
}

type botClientServiceRegisterCurrentPositionServer struct {
	grpc.ServerStream
}

func (x *botClientServiceRegisterCurrentPositionServer) SendAndClose(m *MessageRecieved) error {
	return x.ServerStream.SendMsg(m)
}

func (x *botClientServiceRegisterCurrentPositionServer) Recv() (*Point, error) {
	m := new(Point)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _BotClientService_RegisterRobot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GridPositions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotClientServiceServer).RegisterRobot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.BotClientService/RegisterRobot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotClientServiceServer).RegisterRobot(ctx, req.(*GridPositions))
	}
	return interceptor(ctx, in, info, handler)
}

var _BotClientService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.BotClientService",
	HandlerType: (*BotClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterRobot",
			Handler:    _BotClientService_RegisterRobot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterCurrentPosition",
			Handler:       _BotClientService_RegisterCurrentPosition_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "theHive/proto/botClientService.proto",
}
