trigger:
- main

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: ubuntu-latest

steps:
- task: GoTool@0
  displayName: Install go v1.18
  inputs:
    version: '1.18'

- task: Go@0
  displayName: Build Wall-e
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)/walle/Robot/app'
- task: Go@0
  displayName: Test Wall-e
  inputs:
    command: 'custom'
    customCommand: 'test'
    arguments: './... -v'
    workingDirectory: '$(System.DefaultWorkingDirectory)/walle/Robot/'

- task: Go@0
  displayName: Build The Hive
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)/theHive/app/'

- task: Go@0
  displayName: Test The Hive
  inputs:
    command: 'custom'
    customCommand: 'test'
    arguments: './... -v'
    workingDirectory: '$(System.DefaultWorkingDirectory)/theHive/'

- task: Go@0
  displayName: Build OrderSupplier
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)/orderSupplier/app/'
- task: Go@0
  displayName: Test OrderSupplier
  inputs:
    command: 'custom'
    customCommand: 'test'
    arguments: './... -v'
    workingDirectory: '$(System.DefaultWorkingDirectory)/orderSupplier/'